export interface PlanFeatureResponseDTO {
    featureCode: string;
    limitValue: number;
    isEnabled: boolean;
}

export enum FeatureCodeEnum {
    DASHBOARD_ADVANCED_FILTERS = "DASHBOARD_ADVANCED_FILTERS",
    ACCOUNTS_LIMIT = "ACCOUNTS_LIMIT",
    CREDIT_CARDS_LIMIT = "CREDIT_CARDS_LIMIT",
    CATEGORIES_LIMIT = "CATEGORIES_LIMIT",
    TRANSACTIONS_LIMIT = "TRANSACTIONS_LIMIT",
    TRANSACTION_HISTORY_MONTHS = "TRANSACTION_HISTORY_MONTHS",
    ADVANCED_TRANSACTION_SEARCH = "ADVANCED_TRANSACTION_SEARCH"
}