export enum PeriodFilterRequestDTO {
    CURRENT_MONTH = 'CURRENT_MONTH',
    LAST_MONTH = 'LAST_MONTH',
    LAST_3_MONTHS = 'LAST_3_MONTHS',
    LAST_6_MONTHS = 'LAST_6_MONTHS',
    CURRENT_YEAR = 'CURRENT_YEAR',
    LAST_YEAR = 'LAST_YEAR'
}