name: Deploy Capacitor App to Play Store

on:
    push:
      branches:
        - feature/*
    workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: 20

      - name: Setup JDK
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: '21'

      - name: Install dependencies
        run: |
             cd xpenbox-front
             npm install

      - name: Build Angular
        run: |
             cd xpenbox-front
             npm run build

      - name: Sync Capacitor
        run: |
             cd xpenbox-front
             npx cap sync android

      - name: Decode Keystore
        run: |
          echo "${{ secrets.KEYSTORE_FILE }}" | base64 -d > xpenbox-front/android/app/keystore.jks

      - name: Build Android AAB
        run: |
          cd xpenbox-front/android
          ./gradlew bundleRelease

      - name: Upload to Play Store
        uses: r0adkll/upload-google-play@v1
        with:
          serviceAccountJsonPlainText: ${{ secrets.GOOGLE_PLAY_SERVICE_ACCOUNT_JSON }}
          packageName: com.firstcode.xpenbox
          releaseFiles: xpenbox-front/android/app/build/outputs/bundle/release/app-release.aab
          track: internal
          status: completed